/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonCommonAdminUserCard: typeof import('./src/components/common/CommonAdminUserCard.vue')['default']
    CommonCommonDialog: typeof import('./src/components/common/CommonDialog.vue')['default']
    CommonCommonShowForm: typeof import('./src/components/common/CommonShowForm.vue')['default']
    CommonCommonTable: typeof import('./src/components/common/CommonTable.vue')['default']
    CommonIndexPage: typeof import('./src/components/common/indexPage.vue')['default']
    InputsDynamicInput: typeof import('./src/components/inputs/DynamicInput.vue')['default']
    InputsFormWrapper: typeof import('./src/components/inputs/FormWrapper.vue')['default']
    InputsIsRequired: typeof import('./src/components/inputs/IsRequired.vue')['default']
    InputsPasswordInput: typeof import('./src/components/inputs/PasswordInput.vue')['default']
    LayoutsDashboardMainLayout: typeof import('./src/components/layouts/dashboard/MainLayout.vue')['default']
    LayoutsDashboardNotificationsMenu: typeof import('./src/components/layouts/dashboard/NotificationsMenu.vue')['default']
    LayoutsDashboardSideMenu: typeof import('./src/components/layouts/dashboard/SideMenu.vue')['default']
    LayoutsDashboardTopBar: typeof import('./src/components/layouts/dashboard/TopBar.vue')['default']
    LayoutsDashboardUserMenu: typeof import('./src/components/layouts/dashboard/UserMenu.vue')['default']
    PagesAdminCarriersIndexModule: typeof import('./src/components/pages/admin/carriers/indexModule.vue')['default']
    PagesAdminShippersIndexModule: typeof import('./src/components/pages/admin/ShippersIndexModule.vue')['default']
    PagesAdsAdForm: typeof import('./src/components/pages/ads/AdForm.vue')['default']
    PagesAdsAdShow: typeof import('./src/components/pages/ads/AdShow.vue')['default']
    PagesAuthAuthForm: typeof import('./src/components/pages/auth/AuthForm.vue')['default']
    PagesAuthLoginCardImage: typeof import('./src/components/pages/auth/login/CardImage.vue')['default']
    PagesAuthLoginLoginForm: typeof import('./src/components/pages/auth/login/LoginForm.vue')['default']
    PagesAuthRegisterCardImage: typeof import('./src/components/pages/auth/register/CardImage.vue')['default']
    PagesAuthRegisterCertificatesForm: typeof import('./src/components/pages/auth/register/CertificatesForm.vue')['default']
    PagesAuthRegisterLocationForm: typeof import('./src/components/pages/auth/register/LocationForm.vue')['default']
    PagesAuthRegisterPersonalInfoForm: typeof import('./src/components/pages/auth/register/PersonalInfoForm.vue')['default']
    PagesAuthRegisterSecurityForm: typeof import('./src/components/pages/auth/register/SecurityForm.vue')['default']
    PagesAuthRegisterShipperCourierForm: typeof import('./src/components/pages/auth/register/ShipperCourierForm.vue')['default']
    PagesOffers: typeof import('./src/components/pages/offers/index.vue')['default']
    PagesProfileProfileCard: typeof import('./src/components/pages/profile/ProfileCard.vue')['default']
    PageView: typeof import('./src/components/PageView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonsAdsSkeleton: typeof import('./src/components/skeletons/AdsSkeleton.vue')['default']
    SkeletonsShowSkeleton: typeof import('./src/components/skeletons/ShowSkeleton.vue')['default']
    SkeletonsTableSkeleton: typeof import('./src/components/skeletons/TableSkeleton.vue')['default']
  }
}
